package py.com.pol.opendatagui.entity;

// Generated Sep 30, 2014 8:25:31 AM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Embeddable;
import javax.validation.constraints.Size;

/**
 * MueblesId generated by hbm2java
 */
@Embeddable
public class MueblesId implements java.io.Serializable {

	private String unidadJerarquica;
	private String codigoReparticion;
	private String nombreReparticion;
	private String codigoDependencia;
	private String nombreDependencia;
	private String area;
	private String cuenta;
	private String subcuenta;
	private String especificacion;
	private String descripcion;
	private String fechaAdquisicion;
	private String rotulado;
	private BigDecimal cantidad;
	private BigDecimal valorUnitario;
	private BigDecimal valorTotal;
	private String estadoConservacion;
	private String diferencia;
	private String barras;
	private String departamento;

	public MueblesId() {
	}

	public MueblesId(String unidadJerarquica, String codigoReparticion,
			String nombreReparticion, String codigoDependencia,
			String nombreDependencia, String area, String cuenta,
			String subcuenta, String especificacion, String descripcion,
			String fechaAdquisicion, String rotulado, BigDecimal cantidad,
			BigDecimal valorUnitario, BigDecimal valorTotal,
			String estadoConservacion, String diferencia, String barras,
			String departamento) {
		this.unidadJerarquica = unidadJerarquica;
		this.codigoReparticion = codigoReparticion;
		this.nombreReparticion = nombreReparticion;
		this.codigoDependencia = codigoDependencia;
		this.nombreDependencia = nombreDependencia;
		this.area = area;
		this.cuenta = cuenta;
		this.subcuenta = subcuenta;
		this.especificacion = especificacion;
		this.descripcion = descripcion;
		this.fechaAdquisicion = fechaAdquisicion;
		this.rotulado = rotulado;
		this.cantidad = cantidad;
		this.valorUnitario = valorUnitario;
		this.valorTotal = valorTotal;
		this.estadoConservacion = estadoConservacion;
		this.diferencia = diferencia;
		this.barras = barras;
		this.departamento = departamento;
	}

	@Column(name = "unidad_jerarquica", length = 500)
	@Size(max = 500)
	public String getUnidadJerarquica() {
		return this.unidadJerarquica;
	}

	public void setUnidadJerarquica(String unidadJerarquica) {
		this.unidadJerarquica = unidadJerarquica;
	}

	@Column(name = "codigo_reparticion", length = 500)
	@Size(max = 500)
	public String getCodigoReparticion() {
		return this.codigoReparticion;
	}

	public void setCodigoReparticion(String codigoReparticion) {
		this.codigoReparticion = codigoReparticion;
	}

	@Column(name = "nombre_reparticion", length = 500)
	@Size(max = 500)
	public String getNombreReparticion() {
		return this.nombreReparticion;
	}

	public void setNombreReparticion(String nombreReparticion) {
		this.nombreReparticion = nombreReparticion;
	}

	@Column(name = "codigo_dependencia", length = 500)
	@Size(max = 500)
	public String getCodigoDependencia() {
		return this.codigoDependencia;
	}

	public void setCodigoDependencia(String codigoDependencia) {
		this.codigoDependencia = codigoDependencia;
	}

	@Column(name = "nombre_dependencia", length = 500)
	@Size(max = 500)
	public String getNombreDependencia() {
		return this.nombreDependencia;
	}

	public void setNombreDependencia(String nombreDependencia) {
		this.nombreDependencia = nombreDependencia;
	}

	@Column(name = "area", length = 500)
	@Size(max = 500)
	public String getArea() {
		return this.area;
	}

	public void setArea(String area) {
		this.area = area;
	}

	@Column(name = "cuenta", length = 500)
	@Size(max = 500)
	public String getCuenta() {
		return this.cuenta;
	}

	public void setCuenta(String cuenta) {
		this.cuenta = cuenta;
	}

	@Column(name = "subcuenta", length = 500)
	@Size(max = 500)
	public String getSubcuenta() {
		return this.subcuenta;
	}

	public void setSubcuenta(String subcuenta) {
		this.subcuenta = subcuenta;
	}

	@Column(name = "especificacion", length = 500)
	@Size(max = 500)
	public String getEspecificacion() {
		return this.especificacion;
	}

	public void setEspecificacion(String especificacion) {
		this.especificacion = especificacion;
	}

	@Column(name = "descripcion", length = 500)
	@Size(max = 500)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "fecha_adquisicion", length = 50)
	@Size(max = 50)
	public String getFechaAdquisicion() {
		return this.fechaAdquisicion;
	}

	public void setFechaAdquisicion(String fechaAdquisicion) {
		this.fechaAdquisicion = fechaAdquisicion;
	}

	@Column(name = "rotulado", length = 500)
	@Size(max = 500)
	public String getRotulado() {
		return this.rotulado;
	}

	public void setRotulado(String rotulado) {
		this.rotulado = rotulado;
	}

	@Column(name = "cantidad", precision = 22, scale = 0)
	public BigDecimal getCantidad() {
		return this.cantidad;
	}

	public void setCantidad(BigDecimal cantidad) {
		this.cantidad = cantidad;
	}

	@Column(name = "valor_unitario", precision = 22, scale = 0)
	public BigDecimal getValorUnitario() {
		return this.valorUnitario;
	}

	public void setValorUnitario(BigDecimal valorUnitario) {
		this.valorUnitario = valorUnitario;
	}

	@Column(name = "valor_total", precision = 22, scale = 0)
	public BigDecimal getValorTotal() {
		return this.valorTotal;
	}

	public void setValorTotal(BigDecimal valorTotal) {
		this.valorTotal = valorTotal;
	}

	@Column(name = "estado_conservacion", length = 500)
	@Size(max = 500)
	public String getEstadoConservacion() {
		return this.estadoConservacion;
	}

	public void setEstadoConservacion(String estadoConservacion) {
		this.estadoConservacion = estadoConservacion;
	}

	@Column(name = "diferencia", length = 500)
	@Size(max = 500)
	public String getDiferencia() {
		return this.diferencia;
	}

	public void setDiferencia(String diferencia) {
		this.diferencia = diferencia;
	}

	@Column(name = "barras", length = 500)
	@Size(max = 500)
	public String getBarras() {
		return this.barras;
	}

	public void setBarras(String barras) {
		this.barras = barras;
	}

	@Column(name = "departamento", length = 100)
	@Size(max = 100)
	public String getDepartamento() {
		return this.departamento;
	}

	public void setDepartamento(String departamento) {
		this.departamento = departamento;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof MueblesId))
			return false;
		MueblesId castOther = (MueblesId) other;

		return ((this.getUnidadJerarquica() == castOther.getUnidadJerarquica()) || (this
				.getUnidadJerarquica() != null
				&& castOther.getUnidadJerarquica() != null && this
				.getUnidadJerarquica().equals(castOther.getUnidadJerarquica())))
				&& ((this.getCodigoReparticion() == castOther
						.getCodigoReparticion()) || (this
						.getCodigoReparticion() != null
						&& castOther.getCodigoReparticion() != null && this
						.getCodigoReparticion().equals(
								castOther.getCodigoReparticion())))
				&& ((this.getNombreReparticion() == castOther
						.getNombreReparticion()) || (this
						.getNombreReparticion() != null
						&& castOther.getNombreReparticion() != null && this
						.getNombreReparticion().equals(
								castOther.getNombreReparticion())))
				&& ((this.getCodigoDependencia() == castOther
						.getCodigoDependencia()) || (this
						.getCodigoDependencia() != null
						&& castOther.getCodigoDependencia() != null && this
						.getCodigoDependencia().equals(
								castOther.getCodigoDependencia())))
				&& ((this.getNombreDependencia() == castOther
						.getNombreDependencia()) || (this
						.getNombreDependencia() != null
						&& castOther.getNombreDependencia() != null && this
						.getNombreDependencia().equals(
								castOther.getNombreDependencia())))
				&& ((this.getArea() == castOther.getArea()) || (this.getArea() != null
						&& castOther.getArea() != null && this.getArea()
						.equals(castOther.getArea())))
				&& ((this.getCuenta() == castOther.getCuenta()) || (this
						.getCuenta() != null && castOther.getCuenta() != null && this
						.getCuenta().equals(castOther.getCuenta())))
				&& ((this.getSubcuenta() == castOther.getSubcuenta()) || (this
						.getSubcuenta() != null
						&& castOther.getSubcuenta() != null && this
						.getSubcuenta().equals(castOther.getSubcuenta())))
				&& ((this.getEspecificacion() == castOther.getEspecificacion()) || (this
						.getEspecificacion() != null
						&& castOther.getEspecificacion() != null && this
						.getEspecificacion().equals(
								castOther.getEspecificacion())))
				&& ((this.getDescripcion() == castOther.getDescripcion()) || (this
						.getDescripcion() != null
						&& castOther.getDescripcion() != null && this
						.getDescripcion().equals(castOther.getDescripcion())))
				&& ((this.getFechaAdquisicion() == castOther
						.getFechaAdquisicion()) || (this.getFechaAdquisicion() != null
						&& castOther.getFechaAdquisicion() != null && this
						.getFechaAdquisicion().equals(
								castOther.getFechaAdquisicion())))
				&& ((this.getRotulado() == castOther.getRotulado()) || (this
						.getRotulado() != null
						&& castOther.getRotulado() != null && this
						.getRotulado().equals(castOther.getRotulado())))
				&& ((this.getCantidad() == castOther.getCantidad()) || (this
						.getCantidad() != null
						&& castOther.getCantidad() != null && this
						.getCantidad().equals(castOther.getCantidad())))
				&& ((this.getValorUnitario() == castOther.getValorUnitario()) || (this
						.getValorUnitario() != null
						&& castOther.getValorUnitario() != null && this
						.getValorUnitario()
						.equals(castOther.getValorUnitario())))
				&& ((this.getValorTotal() == castOther.getValorTotal()) || (this
						.getValorTotal() != null
						&& castOther.getValorTotal() != null && this
						.getValorTotal().equals(castOther.getValorTotal())))
				&& ((this.getEstadoConservacion() == castOther
						.getEstadoConservacion()) || (this
						.getEstadoConservacion() != null
						&& castOther.getEstadoConservacion() != null && this
						.getEstadoConservacion().equals(
								castOther.getEstadoConservacion())))
				&& ((this.getDiferencia() == castOther.getDiferencia()) || (this
						.getDiferencia() != null
						&& castOther.getDiferencia() != null && this
						.getDiferencia().equals(castOther.getDiferencia())))
				&& ((this.getBarras() == castOther.getBarras()) || (this
						.getBarras() != null && castOther.getBarras() != null && this
						.getBarras().equals(castOther.getBarras())))
				&& ((this.getDepartamento() == castOther.getDepartamento()) || (this
						.getDepartamento() != null
						&& castOther.getDepartamento() != null && this
						.getDepartamento().equals(castOther.getDepartamento())));
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getUnidadJerarquica() == null ? 0 : this
						.getUnidadJerarquica().hashCode());
		result = 37
				* result
				+ (getCodigoReparticion() == null ? 0 : this
						.getCodigoReparticion().hashCode());
		result = 37
				* result
				+ (getNombreReparticion() == null ? 0 : this
						.getNombreReparticion().hashCode());
		result = 37
				* result
				+ (getCodigoDependencia() == null ? 0 : this
						.getCodigoDependencia().hashCode());
		result = 37
				* result
				+ (getNombreDependencia() == null ? 0 : this
						.getNombreDependencia().hashCode());
		result = 37 * result
				+ (getArea() == null ? 0 : this.getArea().hashCode());
		result = 37 * result
				+ (getCuenta() == null ? 0 : this.getCuenta().hashCode());
		result = 37 * result
				+ (getSubcuenta() == null ? 0 : this.getSubcuenta().hashCode());
		result = 37
				* result
				+ (getEspecificacion() == null ? 0 : this.getEspecificacion()
						.hashCode());
		result = 37
				* result
				+ (getDescripcion() == null ? 0 : this.getDescripcion()
						.hashCode());
		result = 37
				* result
				+ (getFechaAdquisicion() == null ? 0 : this
						.getFechaAdquisicion().hashCode());
		result = 37 * result
				+ (getRotulado() == null ? 0 : this.getRotulado().hashCode());
		result = 37 * result
				+ (getCantidad() == null ? 0 : this.getCantidad().hashCode());
		result = 37
				* result
				+ (getValorUnitario() == null ? 0 : this.getValorUnitario()
						.hashCode());
		result = 37
				* result
				+ (getValorTotal() == null ? 0 : this.getValorTotal()
						.hashCode());
		result = 37
				* result
				+ (getEstadoConservacion() == null ? 0 : this
						.getEstadoConservacion().hashCode());
		result = 37
				* result
				+ (getDiferencia() == null ? 0 : this.getDiferencia()
						.hashCode());
		result = 37 * result
				+ (getBarras() == null ? 0 : this.getBarras().hashCode());
		result = 37
				* result
				+ (getDepartamento() == null ? 0 : this.getDepartamento()
						.hashCode());
		return result;
	}

}
