package py.com.pol.opendatagui.entity;

// Generated Sep 30, 2014 8:25:31 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Muebles generated by hbm2java
 */
@Entity
@Table(name = "muebles", schema = "public")
public class Muebles implements java.io.Serializable {

	private MueblesId id;

	public Muebles() {
	}

	public Muebles(MueblesId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "unidadJerarquica", column = @Column(name = "unidad_jerarquica", length = 500)),
			@AttributeOverride(name = "codigoReparticion", column = @Column(name = "codigo_reparticion", length = 500)),
			@AttributeOverride(name = "nombreReparticion", column = @Column(name = "nombre_reparticion", length = 500)),
			@AttributeOverride(name = "codigoDependencia", column = @Column(name = "codigo_dependencia", length = 500)),
			@AttributeOverride(name = "nombreDependencia", column = @Column(name = "nombre_dependencia", length = 500)),
			@AttributeOverride(name = "area", column = @Column(name = "area", length = 500)),
			@AttributeOverride(name = "cuenta", column = @Column(name = "cuenta", length = 500)),
			@AttributeOverride(name = "subcuenta", column = @Column(name = "subcuenta", length = 500)),
			@AttributeOverride(name = "especificacion", column = @Column(name = "especificacion", length = 500)),
			@AttributeOverride(name = "descripcion", column = @Column(name = "descripcion", length = 500)),
			@AttributeOverride(name = "fechaAdquisicion", column = @Column(name = "fecha_adquisicion", length = 50)),
			@AttributeOverride(name = "rotulado", column = @Column(name = "rotulado", length = 500)),
			@AttributeOverride(name = "cantidad", column = @Column(name = "cantidad", precision = 22, scale = 0)),
			@AttributeOverride(name = "valorUnitario", column = @Column(name = "valor_unitario", precision = 22, scale = 0)),
			@AttributeOverride(name = "valorTotal", column = @Column(name = "valor_total", precision = 22, scale = 0)),
			@AttributeOverride(name = "estadoConservacion", column = @Column(name = "estado_conservacion", length = 500)),
			@AttributeOverride(name = "diferencia", column = @Column(name = "diferencia", length = 500)),
			@AttributeOverride(name = "barras", column = @Column(name = "barras", length = 500)),
			@AttributeOverride(name = "departamento", column = @Column(name = "departamento", length = 100)) })
	public MueblesId getId() {
		return this.id;
	}

	public void setId(MueblesId id) {
		this.id = id;
	}

}
