package py.com.pol.sas.opendata.entity;

// Generated Oct 31, 2014 7:15:20 AM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

/**
 * Departamento generated by hbm2java
 */
@Entity
@Table(name = "departamento", schema = "public")
public class Departamento implements java.io.Serializable {

	private String departamento;
	private BigDecimal poblacion;
	private BigDecimal superficie;
	private BigDecimal densidad;

	public Departamento() {
	}

	public Departamento(String departamento, BigDecimal poblacion,
			BigDecimal superficie, BigDecimal densidad) {
		this.departamento = departamento;
		this.poblacion = poblacion;
		this.superficie = superficie;
		this.densidad = densidad;
	}

	@Id
	@Column(name = "departamento", unique = true, nullable = false, length = 50)
	@NotNull
	@Size(max = 50)
	public String getDepartamento() {
		return this.departamento;
	}

	public void setDepartamento(String departamento) {
		this.departamento = departamento;
	}

	@Column(name = "poblacion", nullable = false, precision = 131089, scale = 0)
	@NotNull
	public BigDecimal getPoblacion() {
		return this.poblacion;
	}

	public void setPoblacion(BigDecimal poblacion) {
		this.poblacion = poblacion;
	}

	@Column(name = "superficie", nullable = false, precision = 22)
	@NotNull
	public BigDecimal getSuperficie() {
		return this.superficie;
	}

	public void setSuperficie(BigDecimal superficie) {
		this.superficie = superficie;
	}

	@Column(name = "densidad", nullable = false, precision = 22)
	@NotNull
	public BigDecimal getDensidad() {
		return this.densidad;
	}

	public void setDensidad(BigDecimal densidad) {
		this.densidad = densidad;
	}

}
