package py.com.pol.sas.opendata.entity;

// Generated Oct 31, 2014 7:15:20 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Tekopora generated by hbm2java
 */
@Entity
@Table(name = "tekopora", schema = "public")
public class Tekopora implements java.io.Serializable {

	private int id;
	private String nroCedula;
	private String nombre;
	private Departamento departamento;
	private String distrito;
	private Double importeMensual;

	public Tekopora() {
	}

	public Tekopora(int id) {
		this.id = id;
	}

	public Tekopora(int id, String nroCedula, String nombre,
			String departamento, String distrito, Double importeMensual) {
		this.id = id;
		this.nroCedula = nroCedula;
		this.nombre = nombre;
		//this.departamento = departamento;
		this.distrito = distrito;
		this.importeMensual = importeMensual;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "nro_cedula")
	public String getNroCedula() {
		return this.nroCedula;
	}

	public void setNroCedula(String nroCedula) {
		this.nroCedula = nroCedula;
	}

	@Column(name = "nombre")
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@ManyToOne(fetch=FetchType.LAZY)
	@JoinColumn(name="id_departamento")
	public Departamento getDepartamento() {
		return this.departamento;
	}

	public void setDepartamento(Departamento departamento) {
		this.departamento = departamento;
	}

	@Column(name = "distrito")
	public String getDistrito() {
		return this.distrito;
	}

	public void setDistrito(String distrito) {
		this.distrito = distrito;
	}

	@Column(name = "importe_mensual", precision = 17, scale = 17)
	public Double getImporteMensual() {
		return this.importeMensual;
	}

	public void setImporteMensual(Double importeMensual) {
		this.importeMensual = importeMensual;
	}

}
